### PR TITLE
Fix column types being treated as strings

### LINKED ISSUE #247: Wrong data types in version 2.9.5
**What happened**:

Hi!

Following upgrade to version 2.9.5, we have a lot of issues with:
* Non table panels (Time series/Pie charts/etc ...)
* Alerting

I dig a bit and I found what I think should be the root cause:
In version 2.9.4, when I'm doing a query in explorer, I have the following result in JSON Inspector:

```
[
  {
    "schema": {
      "refId": "A",
      "meta": {
        "typeVersion": [
          0,
          0
        ],
        "preferredVisualisationType": "table",
        "executedQueryString": "XXXXX"
      },
      "name": "A",
      "fields": [
        {
          "name": "percentage",
          "type": "number",
          "typeInfo": {
            "frame": "float64",
            "nullable": true
          },
          "config": {}
        }
      ]
    },
    "data": {
      "values": [
        [
          99.98919415403734
        ]
      ]
    }
  }
]
```

But the same Query in 2.9.5:

```
[
  {
    "schema": {
      "refId": "A",
      "meta": {
        "typeVersion": [
          0,
          0
        ],
        "preferredVisualisationType": "table",
        "executedQueryString": "XXXX"
      },
      "name": "A",
      "fields": [
        {
          "name": "percentage",
          "type": "string",
          "typeInfo": {
            "frame": "string",
            "nullable": true
          },
          "config": {}
        }
      ]
    },
    "data": {
      "values": [
        [
          "99.97912607848592"
        ]
      ]
    }
  }
]
```
I checked on many queries and I think it is always the same behavior: values who should be numeric (integer/double) or date are now managed as String. And it break all panels requiring dates and numeric like time series but also alerting because numeric are expected.

**What you expected to happen**:

Athena queries should return expected data types

**How to reproduce it (as minimally and precisely as possible)**:

I haven't test exactly this use case but doing the following query in the explorer should be enough to reproduce the issue:

```
SELECT COUNT(*)
FROM <table>
WHERE 1 = 1
```

In version 2.9.4 the return type is `int64` and in version 2.9.5 it is `string`
You can check it in the Inspector => JSON panel.

If you are not able to reproduce I should be able to provide a full example (I have currently rollback to 2.9.4 so I don't have any 2.9.5 version available).

**Screenshots**

**Anything else we need to know?**:

I think it's related to this MR: https://github.com/grafana/athena-datasource/pull/241

**Environment**:
- Grafana version: 9.5.2
- Plugin version: 2.9.4 and 2.9.5
- OS Grafana is installed on: Docker image `grafana/grafana:9.5.2` (Kubernetes)
- User OS & Browser: Chrome/Linux and Chrome/Mac
- Others: thanks a lot for this plugin, it's really useful !

### PR DESCRIPTION
**Pull request by kevinwcyu**
Fixes #247

Fix is from v1.152.0 of grafana-plugin-sdk-go this is the commit for the fix https://github.com/grafana/grafana-plugin-sdk-go/pull/634

To test run the following query with the provisioned data source:

```sql
SELECT COUNT(*)
FROM cloudfront_logs
WHERE 1 = 1
```

Note: if you use Go workspaces locally, you may need to check out this branch outside of your workspace to test it properly.

### CODE REVIEW

**Comment by idastambuk** [comment]
> #247

Had the same question about tests + the cause of the bug :)

**Comment by kevinwcyu** [comment]
@iwysiu, @idastambuk i'm not really sure which commit fixed the bug. i was working on athena in a go workspace and i didn't even notice the modules were on older versions until i checked out a fresh copy in another directory, so i'm not really sure exactly where it was fixed.

**Comment by iwysiu** [comment]
@kevinwcyu hmm, I guess we can merge for now. It may be worth investigating to see when the fix was introduced and see if we have a test for it

**Comment by kevinwcyu** [comment]
@iwysiu, @idastambuk it was this commit that fixed it https://github.com/grafana/grafana-plugin-sdk-go/pull/634 v1.152.0.

**Comment by fridgepoet** [comment]
Heya @kevinwcyu what do you mean about this not being able to be tested in a workspace?
We can modify the versions still and re-build or pull latest changes in the other workspace repos. I must be missing something. I'm curious!

**Comment by kevinwcyu** [comment]
@fridgepoet, i think i just had a messed up workspace somehow. i had an up-to-date version of the plugin-sdk, but the go.mod file in athena-datasource still has an older version.

**Comment by fridgepoet** [comment]
@kevinwcyu oh... i wonder if the version we specify in athena-datasource's go.mod can possibly override any local changes in the plugin-sdk? that wouldn't make sense, right? that's not how we've been able to use the workspace before. I think?

I'm a bit curious to get to the bottom of this but not in an urgent way. Will keep it in mind next time I work with the workspaces. Thanks for mentioning it

**Pull request merged**
