### PR TITLE
Amazon VPC Flow Logs curated dashboard

### PR DESCRIPTION
**Pull request by andresmgot**
The dashboard includes:
 - Instructions to set it up.
 - A table with some data related to the datasource, table and port selected in the variables.
 - A timestream with the same parameters.

Screenshot from 2021-12-22 16-28-51

Can we add something more?

cc/ @mhausenblas

### CODE REVIEW

**Comment by sarahzinger** [comment]
cool stuff! I'm having some trouble getting this set up locally, maybe when you come back next week we can look at it together to see what I'm doing wrong.

I do see that we need to add this dashboard to the plugin.json so that's part of it, but mostly I'm just having difficulty accessing the logs. 

Thanks for doing this!

**Comment by sarahzinger** [comment]
@andresmgot I think the bugs I was seeing were related to that other cache bug and my own local setup, I was able to load this and it looks good! I'm sure it would be nice to add more things, but I also think just getting people started is probably very helpful :) 

just missing the reference in plugin.json and otherwise i think this is good!

**Comment by andresmgot** [comment]
@mhausenblas no new feedback here, right? Should we merge this and release a new version?

**Comment by mhausenblas** [comment]
Yup, this LGTM (sorry, should have followed up from Slack) and let's :shipit:

**Review by sarahzinger — APPROVED** [review]

**Pull request merged**
