### PR TITLE
A11y: Add a11y lint plugin

### PR DESCRIPTION
**Pull request by idastambuk**
More info in/implements https://github.com/grafana/athena-datasource/issues/29

### CODE REVIEW

**Review by sunker — APPROVED** [review]
Nice! No issues in this project, or will the linter only highlight problems in changed files?

**Review by kevinwcyu — APPROVED** [review]
🙌  nice!

**Review by sarahzinger — APPROVED** [review]
yay! Tested it by adding a lint error! Works for me!
Screenshot 2023-01-04 at 3 34 35 PM

**Comment by idastambuk** [comment]
> Nice! No issues in this project, or will the linter only highlight problems in changed files?

It runs the check in all files it seems, so should be fine project-wise if it passes.

**Pull request merged**
