### PR TITLE
Change levitate to comment instead of show X

### PR DESCRIPTION
**Pull request by sarahzinger**
Reverts grafana/athena-datasource#173

Levitate is a very cool tool but I'm not sure it makes sense for our build to fail on it. 

It looks like there was a breaking change from @grafana/runtime@8.2.1 to @grafana/runtime@9.3.1 where some return types changed, and is causing our ci check to fail.

I'm not entirely sure what the action here _should_ be.

- One solution could be to upgrade to 9.3.1, but I think a good chunk of our users are still on grafana 8.4 or so, so I'm not sure that makes sense. 
- Another could be to open an issue in Grafana saying, "hey looks like there was a breaking change here" but we're a major version behind, it doesn't seem that unexpected to me that breaking changes might exist. It also seems odd that the CI check for that would be in the plugin and not in main grafana. 
- Another possibility that I think we had talked about in the past is making this levitate check something that comments, which is interesting and maybe useful. But would it just be noise to have this on every single pr?

I think for now it might be best to just revert this change, until we've thought more about levitate as a tool. This is interesting and useful information but I'm not sure what to do with it. Maybe it should be some kind of badge or something? Anyway for now I'm proposing we get rid of it. I don't think this is a good pattern for us to merge with breaking CI. 

Let me know if I'm missing something obvious tho! Maybe there's a way to actually just fix the breaking change haha. 

fixes https://github.com/grafana/athena-datasource/issues/188

### CODE REVIEW

**Comment by sunker** [comment]
I thought it already was the case that if Levitate fails, it  _won't_ stop the build and prevent us from merging? cc @vickyyyyyyy 

Regarding what action to take, I guess it depends on how it affects our plugins. If they break for real, we should definitely report a bug/try to fix this in core Grafana. But it seems like [this time](https://github.com/grafana/grafana/pull/52981#issuecomment-1199116102), the Levitate error is just a false positive.

**Comment by vickyyyyyyy** [comment]
> it won't stop the build and prevent us from merging

It won't but what Sarah is saying is that it's not good practice for us to merge with failed CI checks (that are not specifically preventing us from merging).

FWIW, we can remove Levitate from our build checks and replace it with a comment for the report instead (see: https://github.com/grafana/azure-data-explorer-datasource/pull/493). This way we still have visibility on any compatibility issues but we can make a judgement call on if we want to ignore them. WDTY?

**Comment by sunker** [comment]
> FWIW, we can remove Levitate from our build checks and replace it with a comment for the report instead (see: [grafana/azure-data-explorer-datasource#493](https://github.com/grafana/azure-data-explorer-datasource/pull/493)). This way we still have visibility on any compatibility issues but we can make a judgement call on if we want to ignore them. WDTY?

Yes I really like that!

**Review by sunker — APPROVED** [review]

**Comment by sarahzinger** [comment]
@vickyyyyyyy @sunker added the commenter version of it, what do you think? This will show up on every pr which is a bit annoying and possibly noise, but I suppose could be useful data?

**Comment by sarahzinger** [comment]
@vickyyyyyyy I'm game to try it out! Let's see how the team likes it.

**Comment by sunker** [comment]
Great stuff @sarahzinger!

**Pull request merged**
